# Pengaturan tema
remote_theme: mmistakes/minimal-mistakes

# Informasi situs
title: Blog Minimal Saya 丰

description: Blog pribadi dengan tampilan minimalis.
author:
  name: Jack Bos
  bio: Seorang penulis dan pembuat konten.

# Pengaturan kustom
social:
  - title: GitHub
    url: https://github.com/getbos
  - title: Twitter
    url: https://twitter.com/getbos

# Pengaturan CSS tambahan
sass:
  style: compressed

# Pengaturan kustom CSS
custom_css:
  - assets/css/custom.css
