# Pengaturan tema
theme: jekyll-theme-slate

# Pengaturan judul situs
title: GetBos 丰

# Pengaturan CSS tambahan
sass:
  style: compressed

# Pengaturan kustom CSS
custom_css:
  - assets/css/custom.css
