# Konfigurasi Jekyll
title: "GetBos Web"
description: "Situs Web GetBos"
theme: "jekyll/minimal-mistakes"
url: "https://getbos.github.io"

# Pengaturan GitHub Pages
repository: "getbos/getbos.github.io"
branch: "main"
