remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

# Konfigurasi tema Minimal Mistakes
minimal_mistakes_skin: default
minimal_mistakes_sidebar: left
minimal_mistakes_social_links:
  github: username
  twitter: username
  facebook: username
  instagram: username
  linkedin: username
  rss: false
  email: false
  dribbble: false
  behance: false
  gitlab: false
  google-plus: false
  pinterest: false
  medium: false
  pocket: false
  reddit: false
  spotify: false
  stackexchange: false
  stackoverflow: false
  lastfm: false
  twitch: false
  vk: false
  weibo: false
  youtube: false

# Menambahkan CSS kustom
stylesheets:
  - "/assets/css/custom.css"
