# _config.yml

baseurl: "https://getbos.github.io"
title: "GetBos - Gate Economy Trade Bitcoin and Other Stuff"
description: "Your site description goes here."

# Konfigurasi AdSense
adsense:
  script: "<script async src=\"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7304615088166232\" crossorigin=\"anonymous\"></script>"
