# _config.yml

baseURL: "https://getbos.github.io"
AdSense: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7304615088166232"
     crossorigin="anonymous"></script>
title: GetBos - Gate Economy Trade Bitcoin and Other Stuff

# Nama situs
title: "Nama Situs Anda"

# Deskripsi situs
description: "Deskripsi singkat tentang situs Anda"

# URL situs
url: "https://getbos.github.io"

# Base URL jika situs di-host di subdirektori
baseurl: ""

# Tema yang digunakan (pastikan tema telah diinstal)
theme: "tema-anda"

# Konfigurasi jekyll-paginate (jika menggunakan pagination)
paginate: 5

# Pengaturan lainnya
timezone: "Asia/Jakarta"
locale: "id_ID"

# Pengaturan SEO
meta_title: "Meta Title untuk SEO"
meta_description: "Meta Description untuk SEO"

# Pengaturan GitHub Pages
github:
  is_project_page: false

# Informasi penulis
author:
  name: "Nama Penulis Anda"
  email: "email@domain.com"

# Sosial Media
social:
  twitter: "@username_twitter"
  github: "getbos"

# Pengaturan Google Analytics (jika digunakan)
google_analytics: "UA-XXXXXXXXX-1"
