name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Atur sesuai dengan nama branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install  # Gantilah sesuai dengan manajer paket yang Anda gunakan (npm, yarn, dll.)

      - name: Build
        run: npm run build  # Gantilah dengan skrip build yang sesuai untuk situs web Anda

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/your/build/directory  # Gantilah dengan direktori tempat hasil build Anda

